### ISSUE TITLE
Add option to change the index (of the position)

### ISSUE THREAD

**Issue by hlechner** [corecoding/Vitals#163]
**Describe the new feature you'd like**
A very useful feature from freon is to set the position (left/center/right) and also the index in which the menu will be displayed inside it.

The Vitals already have the position (left/center/right) but not the index, which is really good to better organize the menu when there are others extensions together in the same box.

**Additional context**
Feature on freon:
![image](https://user-images.githubusercontent.com/11244067/90973465-b05b0980-e4f8-11ea-8b0c-fc2183a43fda.png)

Since Vitals is a fork from freon, maybe implementing it will be trivial.

Thanks!

**Comment by KonstantMan** [comment]
Yeah i agree i would love to see this option in Vitals ,especially when you have too many senors the panel positioning is awful

**Comment by KonstantMan** [comment]
So i tried editing the css file and i changed all the classes to have a colored border to point out the fact that i can't find the class that handles the whole panel in order to position it right in the middle and not  slightly of center as it is right now
![Screenshot from 2021-06-17 06-02-47](https://user-images.githubusercontent.com/56481040/122324492-64120780-cf18-11eb-9b74-65e18eecca69.png)

**Comment by corecoding** [comment]
@KonstantMan  this should probably be a separate issue. But with Gnome Shell, you have to first establish the class names inside extension.js.

**Comment by KonstantMan** [comment]
> @KonstantMan  this should probably be a separate issue. But with Gnome Shell, you have to first establish the class names inside extension.js. 

I have created an  issue long ago about that

**Comment by corecoding** [comment]
Update pushed to develop branch. Not quite as granular as the index, but does allow far left and far right.
