### ISSUE TITLE
hide empty groups

### ISSUE THREAD

**Issue by wbolster** [corecoding/Vitals#20]
currently empty groups show up in the menu, with a expander arrow which actually does nothing. see the second and third item in this example:

![image](https://user-images.githubusercontent.com/748944/44657533-73d59f80-a9fd-11e8-8935-3e9e395e3572.png)

it would be nice if those are just completely left out since there is no information.

**Comment by corecoding** [comment]
Today, you can go to Preferences and turn them off. At a later stage, I'll make it so they go off when the system doesn't support Voltage or Fan. The problem is that because the polling is asynchronous, I don't know that certain sensors don't exist until after the menu is drawn. I'll leave this issue open for now.

**Comment by wbolster** [comment]
thanks

**Comment by corecoding** [comment]
Closing, may open again in the future. Thanks :)
