### ISSUE TITLE
Reclaim unused space between sensors.

### ISSUE THREAD

**Issue by m911t** [corecoding/Vitals#265]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

![image](https://user-images.githubusercontent.com/78878262/172668503-5f5a39ee-40ca-4123-8bf8-30d9d49b85ab.png)
As you can see, there's blank space between the used swap space and the cpu usage. Vitals should reclaim this space when possible.

**Comment by corecoding** [comment]
Do you have Fixed Widths turned on in settings?

**Comment by m911t** [comment]
yep

**Comment by corecoding** [comment]
This is how the Fixed Widths feature works. There were several requests to make the sensors in the menu bar not jump. You can turn fixed widths off to reclaim the space.

No doubt your swap space started off with ###.# MB which is why it has extra space. There are tickets #181 and #168 which you may be interested in.
