### ISSUE TITLE
Refresh time smaller than 1

### ISSUE THREAD

**Issue by thefinalflash060** [corecoding/Vitals#311]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I think the title already describes it, but anyway I'll say that I'm interested in being able to set a refresh rate of maybe 0.5 or something like that, but the extension doesn't let me do it.

**Comment by corecoding** [comment]
I like the idea, but unfortunately it would cause many bug tickets. Even today, I get an occasional bug report that someones system is running slow. This is because the round trip it takes to query all of the sensors can sometimes take longer than 1 second. In fact I have thought a few times of bumping the minimum to 2 seconds. But I probably won't do that.
