### ISSUE TITLE
Options to change color of icons+text after threshold

### ISSUE THREAD

**Issue by realKarthikNair** [corecoding/Vitals#396]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

An option to change colors (green, yellow, orange/red for instance) according to thresholds (can be predefined or user defined) would be helpful.. 

Something like this (source: upcoming official system monitoring extension from Gnome)

![image](https://github.com/corecoding/Vitals/assets/78267371/45e033a8-9067-4353-ba03-33ade6370dcb)

**Comment by corecoding** [comment]
Thanks for sharing the news on Gnome's built in system monitor. It looks like they are relying on GTop for their sensor data. It is interesting to think about a future where Vitals could use a similar approach, however it would likely limit Vitals because it shows so much more. For those curious (and my future self) Here are a [few](https://www.omgubuntu.co.uk/2024/01/gnomes-official-system-monitor-extension-for-gnome-shell) [links](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/system-monitor?ref_type=heads).

Regarding the colors, I have always loved the idea. The problem (just more work) comes from a user interface to specify the color, or thresholds. [Over here](https://github.com/corecoding/Vitals/issues/68) we have a discussion started regarding using `/etc/sensors3.conf`. Please feel free to chime in over there, I would love to see this feature be the next one. Going to close this ticket which will link your post to that other thread. Thank you!
